import { Knex } from "knex";
import { tableName } from "../helpers/database-tables";

export type ColorScheme = {
    colorBase100: string,
    colorBase200: string,
    colorBase300: string,
    colorBaseContent: string,
    colorPrimary: string,
    colorPrimaryContent: string,
    colorSecondary: string,
    colorSecondaryContent: string,
    colorAccent: string,
    colorAccentContent: string,
    colorNeutral: string,
    colorNeutralContent: string,
    colorInfo: string,
    colorInfoContent: string,
    colorSuccess: string,
    colorSuccessContent: string,
    colorWarning: string,
    colorWarningContent: string,
    colorError: string,
    colorErrorContent: string,
    radiusSelector: string,
    radiusField: string,
    radiusBox: string,
    sizeSelector: string,
    sizeField: string,
    border: string,
    depth: string,
    noise: string,
}

export type ColorSchemes = {
    light: ColorScheme,
    dark: ColorScheme
}

export async function getColorSchemes(knex: Knex | Knex.Transaction): Promise<ColorSchemes> {

    const rows = await knex
        .table(tableName("config"))
        .whereIn("key", [
            "color-scheme.light.color-base-100",
            "color-scheme.light.color-base-200",
            "color-scheme.light.color-base-300",
            "color-scheme.light.color-base-content",
            "color-scheme.light.color-primary",
            "color-scheme.light.color-primary-content",
            "color-scheme.light.color-secondary",
            "color-scheme.light.color-secondary-content",
            "color-scheme.light.color-accent",
            "color-scheme.light.color-accent-content",
            "color-scheme.light.color-neutral",
            "color-scheme.light.color-neutral-content",
            "color-scheme.light.color-info",
            "color-scheme.light.color-info-content",
            "color-scheme.light.color-success",
            "color-scheme.light.color-success-content",
            "color-scheme.light.color-warning",
            "color-scheme.light.color-warning-content",
            "color-scheme.light.color-error",
            "color-scheme.light.color-error-content",
            "color-scheme.light.radius-selector",
            "color-scheme.light.radius-field",
            "color-scheme.light.radius-box",
            "color-scheme.light.size-selector",
            "color-scheme.light.size-field",
            "color-scheme.light.border",
            "color-scheme.light.depth",
            "color-scheme.light.noise",
            "color-scheme.dark.color-base-100",
            "color-scheme.dark.color-base-200",
            "color-scheme.dark.color-base-300",
            "color-scheme.dark.color-base-content",
            "color-scheme.dark.color-primary",
            "color-scheme.dark.color-primary-content",
            "color-scheme.dark.color-secondary",
            "color-scheme.dark.color-secondary-content",
            "color-scheme.dark.color-accent",
            "color-scheme.dark.color-accent-content",
            "color-scheme.dark.color-neutral",
            "color-scheme.dark.color-neutral-content",
            "color-scheme.dark.color-info",
            "color-scheme.dark.color-info-content",
            "color-scheme.dark.color-success",
            "color-scheme.dark.color-success-content",
            "color-scheme.dark.color-warning",
            "color-scheme.dark.color-warning-content",
            "color-scheme.dark.color-error",
            "color-scheme.dark.color-error-content",
            "color-scheme.dark.radius-selector",
            "color-scheme.dark.radius-field",
            "color-scheme.dark.radius-box",
            "color-scheme.dark.size-selector",
            "color-scheme.dark.size-field",
            "color-scheme.dark.border",
            "color-scheme.dark.depth",
            "color-scheme.dark.noise",
        ])
        .columns([
            "key",
            "value"
        ])
        .select<{ key: string, value: string }[]>();

    return {
        light: {
            colorBase100: rows.find(r => r.key == "color-scheme.light.color-base-100")!.value,
            colorBase200: rows.find(r => r.key == "color-scheme.light.color-base-200")!.value,
            colorBase300: rows.find(r => r.key == "color-scheme.light.color-base-300")!.value,
            colorBaseContent: rows.find(r => r.key == "color-scheme.light.color-base-content")!.value,
            colorPrimary: rows.find(r => r.key == "color-scheme.light.color-primary")!.value,
            colorPrimaryContent: rows.find(r => r.key == "color-scheme.light.color-primary-content")!.value,
            colorSecondary: rows.find(r => r.key == "color-scheme.light.color-secondary")!.value,
            colorSecondaryContent: rows.find(r => r.key == "color-scheme.light.color-secondary-content")!.value,
            colorAccent: rows.find(r => r.key == "color-scheme.light.color-accent")!.value,
            colorAccentContent: rows.find(r => r.key == "color-scheme.light.color-accent-content")!.value,
            colorNeutral: rows.find(r => r.key == "color-scheme.light.color-neutral")!.value,
            colorNeutralContent: rows.find(r => r.key == "color-scheme.light.color-neutral-content")!.value,
            colorInfo: rows.find(r => r.key == "color-scheme.light.color-info")!.value,
            colorInfoContent: rows.find(r => r.key == "color-scheme.light.color-info-content")!.value,
            colorSuccess: rows.find(r => r.key == "color-scheme.light.color-success")!.value,
            colorSuccessContent: rows.find(r => r.key == "color-scheme.light.color-success-content")!.value,
            colorWarning: rows.find(r => r.key == "color-scheme.light.color-warning")!.value,
            colorWarningContent: rows.find(r => r.key == "color-scheme.light.color-warning-content")!.value,
            colorError: rows.find(r => r.key == "color-scheme.light.color-error")!.value,
            colorErrorContent: rows.find(r => r.key == "color-scheme.light.color-error-content")!.value,
            radiusSelector: rows.find(r => r.key == "color-scheme.light.radius-selector")!.value,
            radiusField: rows.find(r => r.key == "color-scheme.light.radius-field")!.value,
            radiusBox: rows.find(r => r.key == "color-scheme.light.radius-box")!.value,
            sizeSelector: rows.find(r => r.key == "color-scheme.light.size-selector")!.value,
            sizeField: rows.find(r => r.key == "color-scheme.light.size-field")!.value,
            border: rows.find(r => r.key == "color-scheme.light.border")!.value,
            depth: rows.find(r => r.key == "color-scheme.light.depth")!.value,
            noise: rows.find(r => r.key == "color-scheme.light.noise")!.value,
        },
        dark: {
            colorBase100: rows.find(r => r.key == "color-scheme.dark.color-base-100")!.value,
            colorBase200: rows.find(r => r.key == "color-scheme.dark.color-base-200")!.value,
            colorBase300: rows.find(r => r.key == "color-scheme.dark.color-base-300")!.value,
            colorBaseContent: rows.find(r => r.key == "color-scheme.dark.color-base-content")!.value,
            colorPrimary: rows.find(r => r.key == "color-scheme.dark.color-primary")!.value,
            colorPrimaryContent: rows.find(r => r.key == "color-scheme.dark.color-primary-content")!.value,
            colorSecondary: rows.find(r => r.key == "color-scheme.dark.color-secondary")!.value,
            colorSecondaryContent: rows.find(r => r.key == "color-scheme.dark.color-secondary-content")!.value,
            colorAccent: rows.find(r => r.key == "color-scheme.dark.color-accent")!.value,
            colorAccentContent: rows.find(r => r.key == "color-scheme.dark.color-accent-content")!.value,
            colorNeutral: rows.find(r => r.key == "color-scheme.dark.color-neutral")!.value,
            colorNeutralContent: rows.find(r => r.key == "color-scheme.dark.color-neutral-content")!.value,
            colorInfo: rows.find(r => r.key == "color-scheme.dark.color-info")!.value,
            colorInfoContent: rows.find(r => r.key == "color-scheme.dark.color-info-content")!.value,
            colorSuccess: rows.find(r => r.key == "color-scheme.dark.color-success")!.value,
            colorSuccessContent: rows.find(r => r.key == "color-scheme.dark.color-success-content")!.value,
            colorWarning: rows.find(r => r.key == "color-scheme.dark.color-warning")!.value,
            colorWarningContent: rows.find(r => r.key == "color-scheme.dark.color-warning-content")!.value,
            colorError: rows.find(r => r.key == "color-scheme.dark.color-error")!.value,
            colorErrorContent: rows.find(r => r.key == "color-scheme.dark.color-error-content")!.value,
            radiusSelector: rows.find(r => r.key == "color-scheme.dark.radius-selector")!.value,
            radiusField: rows.find(r => r.key == "color-scheme.dark.radius-field")!.value,
            radiusBox: rows.find(r => r.key == "color-scheme.dark.radius-box")!.value,
            sizeSelector: rows.find(r => r.key == "color-scheme.dark.size-selector")!.value,
            sizeField: rows.find(r => r.key == "color-scheme.dark.size-field")!.value,
            border: rows.find(r => r.key == "color-scheme.dark.border")!.value,
            depth: rows.find(r => r.key == "color-scheme.dark.depth")!.value,
            noise: rows.find(r => r.key == "color-scheme.dark.noise")!.value,
        }
    }
}
