# ---------- Build Stage ----------
FROM node:20-bookworm-slim AS builder

WORKDIR /app

COPY package*.json ./
RUN npm i

COPY . .
RUN npm run build

# ---------- Production Stage ----------
FROM node:20-bookworm-slim

WORKDIR /app

COPY package*.json ./
RUN npm i --omit=dev

COPY --from=builder /app/build ./build

ENV NODE_ENV=production
EXPOSE 3000

CMD ["node", "build/main.js"]